excerpt_separator: ""
url: http://kindr3d.github.io
title: kindr3d
email:
author: kindr3d
description: Follow us on our journey through RGSoC
paginate: 5
gems: [jekyll-paginate]
google_analytics: